/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodes"];
        put?: never;
        post: operations["createNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exposures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExposures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exposures/private": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPrivateExposure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exposures/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPublicExposure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exposures/{exposureId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteExposure"];
        options?: never;
        head?: never;
        patch: operations["updateExposure"];
        trace?: never;
    };
    "/v1/access-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAccessRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/frps/plugin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["frpsPlugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["configureClientServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/groups/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clientJoinGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/exposures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clientCreateExposure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/exposures/{exposureId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["clientDeleteExposure"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/access-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clientCreateAccessRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/frpc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clientFrpcStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/frpc/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["clientFrpcReload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["clientLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateGroupRequest: {
            groupId: string;
            password: string;
        };
        JoinGroupRequest: {
            password: string;
            deviceName: string;
        };
        JoinGroupResponse: {
            groupId: string;
            deviceId: string;
            deviceToken: string;
        };
        Group: {
            id?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateNodeRequest: {
            name: string;
            serverAddr: string;
            frpsPort: number;
            /** @description Optional frps auth token when the public frps requires one. */
            authToken?: string;
            allowPorts?: components["schemas"]["PortRange"][];
            domainSuffixes?: string[];
        };
        Node: {
            id?: string;
            name?: string;
            serverAddr?: string;
            frpsPort?: number;
            allowPorts?: components["schemas"]["PortRange"][];
            domainSuffixes?: string[];
        };
        PortRange: {
            from: number;
            to: number;
        };
        DeviceAuth: {
            groupId: string;
            deviceId: string;
            deviceToken: string;
        };
        CreatePrivateExposureRequest: components["schemas"]["DeviceAuth"] & {
            name: string;
            localIP: string;
            localPort: number;
        };
        CreatePublicExposureRequest: components["schemas"]["DeviceAuth"] & {
            nodeId: string;
            name: string;
            /** @enum {string} */
            protocol: "tcp" | "udp" | "http" | "https";
            localIP: string;
            localPort: number;
            remotePort?: number;
            domain?: string;
        };
        UpdateExposureRequest: {
            enabled?: boolean;
        };
        Exposure: {
            id?: string;
            groupId?: string;
            deviceId?: string;
            nodeId?: string;
            name?: string;
            /** @enum {string} */
            mode?: "private" | "public";
            protocol?: string;
            localIP?: string;
            localPort?: number;
            remotePort?: number;
            domain?: string;
            enabled?: boolean;
        };
        CreateAccessRouteRequest: components["schemas"]["DeviceAuth"] & {
            exposureId: string;
            bindAddr?: string;
            bindPort: number;
            fallbackBindPort?: number;
        };
        AccessRoute: {
            id?: string;
            groupId?: string;
            deviceId?: string;
            exposureId?: string;
            bindAddr?: string;
            bindPort?: number;
            fallbackBindPort?: number;
        };
        ConfigureServerRequest: {
            baseURL: string;
            frpsHost: string;
            frpsPort: number;
        };
        ClientJoinGroupRequest: {
            groupId: string;
            password: string;
            deviceName: string;
        };
        ClientCreateExposureRequest: {
            /** @enum {string} */
            mode: "private" | "public";
            nodeId?: string;
            name: string;
            /** @enum {string} */
            protocol?: "tcp" | "udp" | "http" | "https";
            localIP: string;
            localPort: number;
            remotePort?: number;
            domain?: string;
        };
        ClientCreateAccessRouteRequest: {
            exposureId: string;
            bindAddr?: string;
            bindPort: number;
            fallbackBindPort?: number;
        };
        ClientState: {
            server?: Record<string, never>;
            group?: Record<string, never>;
            frpc?: Record<string, never>;
        };
        FrpcStatus: {
            running?: boolean;
            pid?: number;
            configPath?: string;
            lastError?: string;
        };
        PluginDecision: {
            reject: boolean;
            reject_reason?: string;
            unchanged?: boolean;
        };
    };
    responses: never;
    parameters: {
        groupId: string;
        nodeId: string;
        exposureId: string;
        xGroupId: string;
        xDeviceId: string;
        /** @description Bearer device token */
        authorization: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    joinGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["groupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGroupRequest"];
            };
        };
        responses: {
            /** @description Device token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinGroupResponse"];
                };
            };
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"][];
                };
            };
        };
    };
    createNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeRequest"];
            };
        };
        responses: {
            /** @description Node created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
        };
    };
    deleteNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["nodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExposures: {
        parameters: {
            query?: {
                groupId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exposures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exposure"][];
                };
            };
        };
    };
    createPrivateExposure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrivateExposureRequest"];
            };
        };
        responses: {
            /** @description Private exposure created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exposure"];
                };
            };
        };
    };
    createPublicExposure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePublicExposureRequest"];
            };
        };
        responses: {
            /** @description Public exposure created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exposure"];
                };
            };
        };
    };
    deleteExposure: {
        parameters: {
            query?: never;
            header: {
                "X-Group-ID": components["parameters"]["xGroupId"];
                "X-Device-ID": components["parameters"]["xDeviceId"];
                /** @description Bearer device token */
                Authorization: components["parameters"]["authorization"];
            };
            path: {
                exposureId: components["parameters"]["exposureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exposure deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateExposure: {
        parameters: {
            query?: never;
            header: {
                "X-Group-ID": components["parameters"]["xGroupId"];
                "X-Device-ID": components["parameters"]["xDeviceId"];
                /** @description Bearer device token */
                Authorization: components["parameters"]["authorization"];
            };
            path: {
                exposureId: components["parameters"]["exposureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExposureRequest"];
            };
        };
        responses: {
            /** @description Exposure updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exposure"];
                };
            };
        };
    };
    createAccessRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccessRouteRequest"];
            };
        };
        responses: {
            /** @description Access route created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRoute"];
                };
            };
        };
    };
    frpsPlugin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description frps plugin decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDecision"];
                };
            };
        };
    };
    configureClientServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigureServerRequest"];
            };
        };
        responses: {
            /** @description Server saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientState"];
                };
            };
        };
    };
    clientJoinGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientJoinGroupRequest"];
            };
        };
        responses: {
            /** @description Group joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientState"];
                };
            };
        };
    };
    clientCreateExposure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreateExposureRequest"];
            };
        };
        responses: {
            /** @description Exposure created and applied locally */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exposure"];
                };
            };
        };
    };
    clientDeleteExposure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exposureId: components["parameters"]["exposureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exposure deleted locally and remotely */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clientCreateAccessRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreateAccessRouteRequest"];
            };
        };
        responses: {
            /** @description Route created and applied locally */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRoute"];
                };
            };
        };
    };
    clientFrpcStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description frpc status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrpcStatus"];
                };
            };
        };
    };
    clientFrpcReload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description frpc reload result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrpcStatus"];
                };
            };
        };
    };
    clientLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent frpc logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
